version: '3'
services:
  jenkins:
    image : jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports:
      - '8081:8080'
    expose:
      - '8080'
    volumes:
      - '/home/jenkins:/var/jenkins_home'
      - /home/ubuntu/logs:/home/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "Asia/Seoul"
